name: XAML CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      # 防止内存不足导致编译崩溃
      CMAKE_JOB_POOLS: "compile=16;link=8"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Essential Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang-15 \
          lldb-15 \
          ninja-build \
          libstdc++-12-dev \
          libx11-xcb-dev \
          libgl1-mesa-glx \
          libdrm-dev \
          libegl1-mesa-dev \
          libfontconfig1-dev \
          libfreetype6-dev

    - name: Setup .NET (Avalonia)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          7.0.x
          6.0.x

    - name: Build with CMake
      timeout-minutes: 30
      run: |
        mkdir -p build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_CXX_COMPILER=clang++-15 \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -GNinja | tee cmake.log
        
        cmake --build . \
          --verbose \
          --parallel $(($(nproc)-1)) | tee build.log
        
        # 符号表检查
        objdump -t ./XamlApp | grep -i avalonia

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: diagnostics-${{ github.run_id }}
        path: |
          build/**/*.log
          build/compile_commands.json
          build/XamlApp
      if: always()  # 即使失败也上传
