name: XAML CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@v4

    # .NET 环境（Avalonia必须）
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
          6.0.x

    # 安装 Linux 图形依赖
    - name: Install X11 deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libgl1-mesa-dev \
          libgbm-dev \
          libdrm-dev \
          libwebkit2gtk-4.0-dev  # 新增WebKit支持

    # 构建
    - name: Build with CMake
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja
        cmake --build . --parallel $(nproc)

    # 新版产物上传方式
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xaml-app-package
        path: |
          build/XamlApp
          build/*.so
          build/*.dll
        compression-level: 9  # 最大压缩
        overwrite: true
